### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by blumenstiel** [aliFrancis/SEnSeI#1]
Thanks for the work!

Could you share the python version used for training and saving the model? I got this error when loading the model: https://stackoverflow.com/questions/72452716/code-marshal-loadsraw-code-valueerror-bad-marshal-data-unknown-type-code

The error occurs because keras/marshal is not upwards/downwards compatible. Thanks!

**Comment by aliFrancis** [comment]
Hi @blumenstiel

I would strongly recommend using the [senseiv2 repo](https://github.com/aliFrancis/SEnSeIv2). This one is from several years ago and has been superseded by the later iteration of SEnSeI.

Ali

**Comment by blumenstiel** [comment]
Thanks a lot, V2 works now! Maybe a link in the Readme would be helpful.
